name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Docker login to Docker Hub
      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: docker build -t mevanmanilka/docker-react:latest -f Dockerfile .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push mevanmanilka/docker-react:latest

      # Prepare Dockerrun.aws.json and zip it
      - name: Package Dockerrun for Elastic Beanstalk
        run: zip deploy.zip Dockerrun.aws.json

      # Ensure AWS credentials are properly set as environment variables
      - name: Set up AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      # Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: frontend
          environment_name: Frontend-env
          version_label: ${{ github.sha }}-${{ github.run_number }}
          deployment_package: deploy.zip
          region: us-east-1
          existing_bucket_name: elasticbeanstalk-us-east-1-724084651959
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
