name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Docker login
      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build Docker image
      - name: Build Docker image
        run: docker build -t mevanmanilka/docker-react:latest -f Dockerfile .

      # 4. Push Docker image
      - name: Push Docker image
        run: docker push mevanmanilka/docker-react:latest

      # 5. Package Dockerrun.aws.json for Elastic Beanstalk
      - name: Package for Elastic Beanstalk
        run: zip -r deploy.zip Dockerrun.aws.json

      # 6. Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        env:                     # <-- MUST be at this level
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-us-east-1-724084651959
          region: us-east-1
          version_label: ${{ github.sha }}-${{ github.run_number }}
          deployment_package: deploy.zip
